name: ampelstatic
channels:
  - ampelproject
  - conda-forge
dependencies:
  - aiohttp==3.5.4
  - aioslacker==0.0.11
  - astropy==3.1.2
  - backoff==1.8.0
  - catshtm==0.1.15
  - configargparse==0.12.0
  - dataclasses==0.6
  - extcats==2.3
  - fastavro==0.21.20
  - graphitesend==0.10.0
  - healpylite==0.1.1
  - iminuit==1.3.3
  - ipython==7.4.0
  - librdkafka==1.2.2
  - jupyter
  - matplotlib 
  - marshaltools==0.0.10
  - numpy==1.16.2
  - palpy==1.8.1
  - pandas==0.24.2
  - psycopg2==2.8.1
  - pycryptodome==3.7.3
  - pydantic==0.14
  - pymongo==3.7.2
  - pytest==4.4.0
  - pytest-cov==2.6.1
  - pytest-mock==1.10.3
  - pytest-pylint==0.14.0
  - python>=3.6
  - python-confluent-kafka==1.1.0
  - pyzmq==18.0.1
  - requests==2.21.0
  - schedule==0.5.0
  - scikit-learn==0.20.3
  - scipy==1.2.1
  - sjcl==0.2.1
  - slackclient==1.3.1
  - sncosmo==1.6.0
  - sncosmo-data==1.6.0
  - sqlalchemy==1.3.2
  - werkzeug==0.15.2
  - zerorpc==0.6.1
  - gdb
  - pip:
    - mongomock==3.16.0
